### ISSUE TITLE
I want to join Syntatis

### ISSUE THREAD

**Issue by kentaurse** [syntatis/wp-plugin-readme-parser#23]
As a proficient developer with extensive experience in PHP, WordPress, and Docker, I am excited about the opportunity to join Syntatis. My background includes creating and enhancing WordPress plugins, developing utility functions, and building Docker environments for PHP and WordPress, making me well-equipped to contribute to Syntatis' mission of providing innovative and efficient syntactic solutions for the web.

**Comment by tfirdaus** [comment]
Hi, @kentaurse. 
Thank you so much for your interest in our project. We’re always open to contributions, so feel free to join in and create a pull request in one of our repositories.
